name: Editorconfig
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: greut/eclint-action@v0
